on: [push]

jobs:
  altwalker-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check the models
      run: altwalker check -m models/default.json "random(vertex_coverage(100))"
      shell: bash

    - name: Setup AltWalker
      uses: altwalker/setup-altwalker@main

    - name: Verify the code
      run: altwalker verify tests -m models/default.json
      shell: bash

    - name: Run the tests
      run: altwalker online tests -m models/default.json "random(vertex_coverage(100))"
      shell: bash

    - name: Generate a test sequence
      run: altwalker offline -m models/default.json "random(vertex_coverage(100))" -f steps/steps.json
      shell: bash

    - name: Run a pre-generated sequence
      run: altwalker walk tests steps/steps.json
      shell: bash

    - name: Archive log files
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: logs
        path: '*.log'
